apiVersion: v1
kind: Service
metadata:
  name: dockercoins
  labels:
    app: dockercoins
    service: dockercoins
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    name: http
  selector:
    app: dockercoins
---