apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockercoins
spec:
  selector:
    matchLabels:
      app: dockercoins
  template:
    metadata:
      labels:
        app: dockercoins
    spec:
      containers:
      - name: rng
        image: gcr.io/rotcaus/dockercoins_rng:v1
        imagePullPolicy: Always
      - name: hasher
        image: gcr.io/rotcaus/dockercoins_hasher:v1
        imagePullPolicy: Always
      - name: webui
        image: gcr.io/rotcaus/dockercoins_webui:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      - name: worker
        image: gcr.io/rotcaus/dockercoins_worker:v1
        imagePullPolicy: Always
      - name: redis
        image: redis
