apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dockercoins
  labels:
    app: {{ .Release.Name }}-dockercoins
    service: {{ .Release.Name }}-dockercoins
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    name: http
  selector:
    app: {{ .Release.Name }}-dockercoins
---
