apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    env:
    - name: MYCONFIG
      valueFrom:
        configMapKeyRef:
          name: app-env-config
          key: debug.level
