apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2020-07-09T23:54:01Z","generation":1,"labels":{"app":"grafana","install.operator.istio.io/owning-resource":"installed-state","install.operator.istio.io/owning-resource-namespace":"istio-system","operator.istio.io/component":"AddonComponents","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.6.4","release":"istio"},"name":"grafana","namespace":"istio-system","resourceVersion":"1515","selfLink":"/apis/apps/v1/namespaces/istio-system/deployments/grafana","uid":"771548cc-1dce-4583-b4e6-1ab8fd70178c"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"grafana"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"sidecar.istio.io/inject":"false"},"creationTimestamp":null,"labels":{"app":"grafana","chart":"grafana","heritage":"Tiller","release":"istio-system"}},"spec":{"affinity":{"nodeAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"preference":{"matchExpressions":[{"key":"beta.kubernetes.io/arch","operator":"In","values":["amd64"]}]},"weight":2},{"preference":{"matchExpressions":[{"key":"beta.kubernetes.io/arch","operator":"In","values":["ppc64le"]}]},"weight":2},{"preference":{"matchExpressions":[{"key":"beta.kubernetes.io/arch","operator":"In","values":["s390x"]}]},"weight":2}],"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"beta.kubernetes.io/arch","operator":"In","values":["amd64","ppc64le","s390x"]}]}]}}},"containers":[{"env":[{"name":"GRAFANA_PORT","value":"3000"},{"name":"GF_AUTH_BASIC_ENABLED","value":"false"},{"name":"GF_AUTH_ANONYMOUS_ENABLED","value":"true"},{"name":"GF_AUTH_ANONYMOUS_ORG_ROLE","value":"Admin"},{"name":"GF_PATHS_DATA","value":"/data/grafana"},{"name":"GF_SERVER_ROOT_URL","value":"%(protocol)s://%(domain)s:/grafana"}],"image":"grafana/grafana:6.7.4","imagePullPolicy":"IfNotPresent","name":"grafana","ports":[{"containerPort":3000,"protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/api/health","port":3000,"scheme":"HTTP"},"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"resources":{"requests":{"cpu":"10m"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/data/grafana","name":"data"},{"mountPath":"/var/lib/grafana/dashboards/istio/istio-mesh-dashboard.json","name":"dashboards-istio-istio-mesh-dashboard","readOnly":true,"subPath":"istio-mesh-dashboard.json"},{"mountPath":"/var/lib/grafana/dashboards/istio/istio-performance-dashboard.json","name":"dashboards-istio-istio-performance-dashboard","readOnly":true,"subPath":"istio-performance-dashboard.json"},{"mountPath":"/var/lib/grafana/dashboards/istio/istio-service-dashboard.json","name":"dashboards-istio-istio-service-dashboard","readOnly":true,"subPath":"istio-service-dashboard.json"},{"mountPath":"/var/lib/grafana/dashboards/istio/istio-workload-dashboard.json","name":"dashboards-istio-istio-workload-dashboard","readOnly":true,"subPath":"istio-workload-dashboard.json"},{"mountPath":"/var/lib/grafana/dashboards/istio/mixer-dashboard.json","name":"dashboards-istio-mixer-dashboard","readOnly":true,"subPath":"mixer-dashboard.json"},{"mountPath":"/var/lib/grafana/dashboards/istio/pilot-dashboard.json","name":"dashboards-istio-pilot-dashboard","readOnly":true,"subPath":"pilot-dashboard.json"},{"mountPath":"/etc/grafana/provisioning/datasources/datasources.yaml","name":"config","subPath":"datasources.yaml"},{"mountPath":"/etc/grafana/provisioning/dashboards/dashboardproviders.yaml","name":"config","subPath":"dashboardproviders.yaml"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{"fsGroup":472,"runAsUser":472},"terminationGracePeriodSeconds":30,"volumes":[{"configMap":{"defaultMode":420,"name":"istio-grafana"},"name":"config"},{"emptyDir":{},"name":"data"},{"configMap":{"defaultMode":420,"name":"istio-grafana-configuration-dashboards-istio-mesh-dashboard"},"name":"dashboards-istio-istio-mesh-dashboard"},{"configMap":{"defaultMode":420,"name":"istio-grafana-configuration-dashboards-istio-performance-dashboard"},"name":"dashboards-istio-istio-performance-dashboard"},{"configMap":{"defaultMode":420,"name":"istio-grafana-configuration-dashboards-istio-service-dashboard"},"name":"dashboards-istio-istio-service-dashboard"},{"configMap":{"defaultMode":420,"name":"istio-grafana-configuration-dashboards-istio-workload-dashboard"},"name":"dashboards-istio-istio-workload-dashboard"},{"configMap":{"defaultMode":420,"name":"istio-grafana-configuration-dashboards-mixer-dashboard"},"name":"dashboards-istio-mixer-dashboard"},{"configMap":{"defaultMode":420,"name":"istio-grafana-configuration-dashboards-pilot-dashboard"},"name":"dashboards-istio-pilot-dashboard"}]}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2020-07-09T23:54:18Z","lastUpdateTime":"2020-07-09T23:54:18Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2020-07-09T23:54:01Z","lastUpdateTime":"2020-07-09T23:54:18Z","message":"ReplicaSet \"grafana-5dc4b4676c\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":1,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2020-07-09T23:54:01Z"
  generation: 2
  labels:
    app: grafana
    install.operator.istio.io/owning-resource: installed-state
    install.operator.istio.io/owning-resource-namespace: istio-system
    operator.istio.io/component: AddonComponents
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.6.4
    release: istio
  name: grafana
  namespace: istio-system
  resourceVersion: "584227"
  selfLink: /apis/apps/v1/namespaces/istio-system/deployments/grafana
  uid: 771548cc-1dce-4583-b4e6-1ab8fd70178c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: grafana
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        app: grafana
        chart: grafana
        heritage: Tiller
        release: istio-system
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
            weight: 2
          - preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - ppc64le
            weight: 2
          - preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - s390x
            weight: 2
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
      containers:
      - env:
        - name: GRAFANA_PORT
          value: "3000"
        - name: GF_AUTH_BASIC_ENABLED
          value: "false"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin
        - name: GF_PATHS_DATA
          value: /data/grafana
        ## ADD GRAFANA ROOT URL ENV
        - name: GF_SERVER_ROOT_URL
          value: '%(protocol)s://%(domain)s:/grafana'
        - name: GF_SERVER_SERVE_FROM_SUB_PATH
          value: "true"
        image: grafana/grafana:6.7.4
        imagePullPolicy: IfNotPresent
        name: grafana
        ports:
        - containerPort: 3000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/health
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 10m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/grafana
          name: data
        - mountPath: /var/lib/grafana/dashboards/istio/istio-mesh-dashboard.json
          name: dashboards-istio-istio-mesh-dashboard
          readOnly: true
          subPath: istio-mesh-dashboard.json
        - mountPath: /var/lib/grafana/dashboards/istio/istio-performance-dashboard.json
          name: dashboards-istio-istio-performance-dashboard
          readOnly: true
          subPath: istio-performance-dashboard.json
        - mountPath: /var/lib/grafana/dashboards/istio/istio-service-dashboard.json
          name: dashboards-istio-istio-service-dashboard
          readOnly: true
          subPath: istio-service-dashboard.json
        - mountPath: /var/lib/grafana/dashboards/istio/istio-workload-dashboard.json
          name: dashboards-istio-istio-workload-dashboard
          readOnly: true
          subPath: istio-workload-dashboard.json
        - mountPath: /var/lib/grafana/dashboards/istio/mixer-dashboard.json
          name: dashboards-istio-mixer-dashboard
          readOnly: true
          subPath: mixer-dashboard.json
        - mountPath: /var/lib/grafana/dashboards/istio/pilot-dashboard.json
          name: dashboards-istio-pilot-dashboard
          readOnly: true
          subPath: pilot-dashboard.json
        - mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
          name: config
          subPath: datasources.yaml
        - mountPath: /etc/grafana/provisioning/dashboards/dashboardproviders.yaml
          name: config
          subPath: dashboardproviders.yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 472
        runAsUser: 472
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: istio-grafana
        name: config
      - emptyDir: {}
        name: data
      - configMap:
          defaultMode: 420
          name: istio-grafana-configuration-dashboards-istio-mesh-dashboard
        name: dashboards-istio-istio-mesh-dashboard
      - configMap:
          defaultMode: 420
          name: istio-grafana-configuration-dashboards-istio-performance-dashboard
        name: dashboards-istio-istio-performance-dashboard
      - configMap:
          defaultMode: 420
          name: istio-grafana-configuration-dashboards-istio-service-dashboard
        name: dashboards-istio-istio-service-dashboard
      - configMap:
          defaultMode: 420
          name: istio-grafana-configuration-dashboards-istio-workload-dashboard
        name: dashboards-istio-istio-workload-dashboard
      - configMap:
          defaultMode: 420
          name: istio-grafana-configuration-dashboards-mixer-dashboard
        name: dashboards-istio-mixer-dashboard
      - configMap:
          defaultMode: 420
          name: istio-grafana-configuration-dashboards-pilot-dashboard
        name: dashboards-istio-pilot-dashboard
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-07-09T23:54:18Z"
    lastUpdateTime: "2020-07-09T23:54:18Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-07-09T23:54:01Z"
    lastUpdateTime: "2020-07-13T07:25:56Z"
    message: ReplicaSet "grafana-6bc57c6c57" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
